apiVersion: v1
data:
 clusternetworkprofile_overrides: |
  config_overrides:
    connectivity_checker:
      error_pods_reporting_enable: true
      reachability_test_enable:
        periodic_sync:
          enable_updates: true
          interval: 120
        external_url:
          url: 'google.com'
      reachability_tests:
        - pod_to_pod
        - pod_to_node
        - pod_to_clusterIP
        - pod_to_service
        - pod_to_LB_VIP
        - pod_to_NodePort
        - pod_to_External
        - node_to_node
        - node_to_pod
        - node_to_clusterIP
        - node_to_LB_VIP
    registry:
      image_prefix: quay.io/noirolabs
      network_operator_version: cko-mvp-1
    aci_config:
      cluster_l3out:
        aep: infra_aaep
        svi:
          floating_ip: 192.168.12.100/24
          secondary_ip: 192.168.12.254/24
          vlan_id: 272       
          mtu: 9000
        bgp:
          peering:
            remote_as_number: 64602
            aci_as_number: 65001
      l3out:
        name: calico2-rtr-l3out
        external_networks:
        - calico2-rtr-extepg
      vrf:
        name: calico2_vrf
        tenant: calico2
    net_config:
      node_subnet: 192.168.12.0/24
      pod_subnet: 10.2.0.0/16
      extern_dynamic: 10.72.0.0/16
      cluster_svc_subnet: 10.96.0.0/12
    topology:
      rack:
      - id: 1
        aci_pod_id: 1
        leaf:
        - id: 101
          local_ip: 192.168.12.251
        - id: 102
          local_ip: 192.168.12.252
        node:
        - name: calico2-node-1           # K8s nodes
        - name: calico2-node-2
        - name: calico2-node-3
    fabricinfra:
      name: krk-dmz-fab1
    cni: calico
kind: ConfigMap
metadata:
  name: calico2
  namespace: netop-manager
  labels:
    cluster_name: calico2
    distro: kubernetes
    location: krk-dmz
    pod-network: calico
