apiVersion: netop.mgr/v1alpha1
kind: ClusterGroupProfile
metadata:
  name: openshift-clusters
  namespace: netop-manager
  labels:
    distro: openshift
    location: krk-dmz
    release: "4.10"
    platform: esx
    pod-network: aci-cni
spec:
  selector:
    matchLabels:
      fabric: krk-dmz-fab1
      site: krk-dmz
  config_overrides:
    cni: aci
    distro:
      type: openshift
      release: "4.10"
      platform: esx
    connectivity_checker:
      error_pods_reporting_enable: true
      reachability_test_enable:
        periodic_sync:
          enable_updates: true
          interval: 120
        external_url:
          url: 'cisco.com'
      reachability_tests:
        - pod_to_pod
        - pod_to_node
        - pod_to_clusterIP
        - pod_to_service
        - pod_to_LB_VIP
        - pod_to_NodePort
        - pod_to_External
        - node_to_node
        - node_to_pod
        - node_to_clusterIP
        - node_to_LB_VIP
